#ifndef EMM_INDEX_H_
#define EMM_INDEX_H_

#define UARHO1  0
#define UARHO2  1
#define UMX     2
#define UMY     3
#define UMZ     4
#define URHOE   5
#define NCONS   6
#define GALPHA  6
#define NV      7
#define GPRESS  7
#define GT1     8
#define GT2     9
#define NV2     10

#define QALPHA  0
#define QRHO1   1
#define QRHO2   2
#define QU      3
#define QV      4
#define QW      5
#define QPRES   6
#define NPRIM   7

#define ORHO   0
#define OE     1
#define OSOS   2
#endif